title: "Lorenzo Forni"
email: "lorenzo.forni@unipd.it; lorenzo.forni@prometeia.com; lorenzo.forni@cfp.pt"
description: "Economist | Professor | Policy Advisor | Author "
baseurl: "" # leave empty for personal GitHub Pages
url: "https://lorenzoforni.github.io"

author:
  name: "Lorenzo Forni"
  avatar: "assets/img/profile.jpg"
  bio: "Economist, academic, and policy advisor. I work at the intersection of economics, sustainability, and public finance."
  location: "Italy | U.S. | Portugal"
  email: "lorenzo@example.com"
  scholar: "https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=lorenzo+forni&oq=lore"
  linkedin: "https://www.linkedin.com/in/lorenzoforni/"
  github: "https://github.com/lorenzo.forni"
  orcid: "https://orcid.org/0000-0002-2237-122X"

# Social links
social:
  - icon: fas fa-envelope
    url: "mailto:lorenzo@example.com"
  - icon: fab fa-linkedin
    url: "https://www.linkedin.com/in/lorenzoforni/"
  - icon: fab fa-google
    url: "https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=lorenzo+forni&oq=lore"
  - icon: fab fa-github
    url: "https://github.com/lorenzo.forni"

# Navigation
navigation:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
markdown: kramdown
highlighter: rouge
